[project]
name = "polysurf"
version = "0.2.0"
description = "Construtor simplificado de sistemas slab + polímero usando ASE"
authors = [
  {name = "Gabriel Barbosa", email = "gabriel@example.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
  "numpy",
  "scipy",
  "ase",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "black",
  "isort",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["polysurf*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
